/**
 * generated by Xtext 2.39.0
 */
package fr.n7.pDL1;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ressources</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.Ressources#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.pDL1.Ressources#getNb_ressources <em>Nb ressources</em>}</li>
 *   <li>{@link fr.n7.pDL1.Ressources#getUseressources <em>Useressources</em>}</li>
 * </ul>
 *
 * @see fr.n7.pDL1.PDL1Package#getRessources()
 * @model
 * @generated
 */
public interface Ressources extends ProcessElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.pDL1.PDL1Package#getRessources_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.Ressources#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Nb ressources</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nb ressources</em>' attribute.
   * @see #setNb_ressources(int)
   * @see fr.n7.pDL1.PDL1Package#getRessources_Nb_ressources()
   * @model
   * @generated
   */
  int getNb_ressources();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.Ressources#getNb_ressources <em>Nb ressources</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nb ressources</em>' attribute.
   * @see #getNb_ressources()
   * @generated
   */
  void setNb_ressources(int value);

  /**
   * Returns the value of the '<em><b>Useressources</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.pDL1.UseRessources}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Useressources</em>' containment reference list.
   * @see fr.n7.pDL1.PDL1Package#getRessources_Useressources()
   * @model containment="true"
   * @generated
   */
  EList<UseRessources> getUseressources();

} // Ressources
