/**
 * generated by Xtext 2.39.0
 */
package fr.n7.pDL1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Use Ressources</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.UseRessources#getQuantity <em>Quantity</em>}</li>
 *   <li>{@link fr.n7.pDL1.UseRessources#getRessources <em>Ressources</em>}</li>
 * </ul>
 *
 * @see fr.n7.pDL1.PDL1Package#getUseRessources()
 * @model
 * @generated
 */
public interface UseRessources extends EObject
{
  /**
   * Returns the value of the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantity</em>' attribute.
   * @see #setQuantity(int)
   * @see fr.n7.pDL1.PDL1Package#getUseRessources_Quantity()
   * @model
   * @generated
   */
  int getQuantity();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.UseRessources#getQuantity <em>Quantity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantity</em>' attribute.
   * @see #getQuantity()
   * @generated
   */
  void setQuantity(int value);

  /**
   * Returns the value of the '<em><b>Ressources</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ressources</em>' reference.
   * @see #setRessources(Ressources)
   * @see fr.n7.pDL1.PDL1Package#getUseRessources_Ressources()
   * @model
   * @generated
   */
  Ressources getRessources();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.UseRessources#getRessources <em>Ressources</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ressources</em>' reference.
   * @see #getRessources()
   * @generated
   */
  void setRessources(Ressources value);

} // UseRessources
