/**
 * generated by Xtext 2.39.0
 */
package fr.n7.pDL1.impl;

import fr.n7.pDL1.PDL1Package;
import fr.n7.pDL1.Ressources;
import fr.n7.pDL1.UseRessources;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ressources</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.impl.RessourcesImpl#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.pDL1.impl.RessourcesImpl#getNb_ressources <em>Nb ressources</em>}</li>
 *   <li>{@link fr.n7.pDL1.impl.RessourcesImpl#getUseressources <em>Useressources</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RessourcesImpl extends ProcessElementImpl implements Ressources
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getNb_ressources() <em>Nb ressources</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNb_ressources()
   * @generated
   * @ordered
   */
  protected static final int NB_RESSOURCES_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getNb_ressources() <em>Nb ressources</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNb_ressources()
   * @generated
   * @ordered
   */
  protected int nb_ressources = NB_RESSOURCES_EDEFAULT;

  /**
   * The cached value of the '{@link #getUseressources() <em>Useressources</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUseressources()
   * @generated
   * @ordered
   */
  protected EList<UseRessources> useressources;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RessourcesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PDL1Package.Literals.RESSOURCES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PDL1Package.RESSOURCES__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getNb_ressources()
  {
    return nb_ressources;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNb_ressources(int newNb_ressources)
  {
    int oldNb_ressources = nb_ressources;
    nb_ressources = newNb_ressources;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PDL1Package.RESSOURCES__NB_RESSOURCES, oldNb_ressources, nb_ressources));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<UseRessources> getUseressources()
  {
    if (useressources == null)
    {
      useressources = new EObjectContainmentEList<UseRessources>(UseRessources.class, this, PDL1Package.RESSOURCES__USERESSOURCES);
    }
    return useressources;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PDL1Package.RESSOURCES__USERESSOURCES:
        return ((InternalEList<?>)getUseressources()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PDL1Package.RESSOURCES__NAME:
        return getName();
      case PDL1Package.RESSOURCES__NB_RESSOURCES:
        return getNb_ressources();
      case PDL1Package.RESSOURCES__USERESSOURCES:
        return getUseressources();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PDL1Package.RESSOURCES__NAME:
        setName((String)newValue);
        return;
      case PDL1Package.RESSOURCES__NB_RESSOURCES:
        setNb_ressources((Integer)newValue);
        return;
      case PDL1Package.RESSOURCES__USERESSOURCES:
        getUseressources().clear();
        getUseressources().addAll((Collection<? extends UseRessources>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PDL1Package.RESSOURCES__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PDL1Package.RESSOURCES__NB_RESSOURCES:
        setNb_ressources(NB_RESSOURCES_EDEFAULT);
        return;
      case PDL1Package.RESSOURCES__USERESSOURCES:
        getUseressources().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PDL1Package.RESSOURCES__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PDL1Package.RESSOURCES__NB_RESSOURCES:
        return nb_ressources != NB_RESSOURCES_EDEFAULT;
      case PDL1Package.RESSOURCES__USERESSOURCES:
        return useressources != null && !useressources.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", nb_ressources: ");
    result.append(nb_ressources);
    result.append(')');
    return result.toString();
  }

} //RessourcesImpl
