simple_autoencoder = Sequential(name = "simple_autoencoder")
simple_autoencoder.add(Input(shape=(n_input,)))
simple_autoencoder.add(Dense(n_latent, activation='relu',name="encoder_layer"))
simple_autoencoder.add(Dense(n_input, activation='sigmoid', name = "decoder_layer" ))
simple_autoencoder.summary()